### ISSUE TITLE
nao_leds_effects/LedEffect.h: and naoqi_bridge_msgs/TactileTouch.h: No such file or directory

### ISSUE THREAD

**Issue by mxochicale** [FelipMarti/nao_examples#1]
Hiya, I have tried to build the nao_examples package on a machine with Ubuntu 16.05 with ROS kinetic and NAOqi 2.14.13. However, I am not entirely sure how to solve this issue with the following header dependencies, the original repo doesn't have such headers.
```
~/catkin_ws/src/nao_examples/nao_leds_effects/include/nao_leds_effects_node.h:16:40: fatal error: nao_leds_effects/LedEffect.h: No such file or directory
~/catkin_ws/src/nao_examples/nao_tactile_interface/include/nao_tactile_interface_node.h:22:44: fatal error: naoqi_bridge_msgs/TactileTouch.h: No such file or directory
```
Any suggestion?

**Comment by FelipMarti** [comment]
Hi Miguel,

I think there are 2 different errors. I've been able to fix this one:
`naoqi_bridge_msgs/TactileTouch.h: No such file or directory`

This error occurred due to a [modification of the naoqi_bridge_msg](https://github.com/ros-naoqi/nao_robot/pull/29) from TactileTouch to HeadTouch.

The other error I think is a build dependency problem, but I haven't been able to reproduce it. So, it seems that the package compiles without errors.

Thanks for your feedback.
